wandb_version: 1

Train Batch Size:
  desc: null
  value: 4
Test Batch Size:
  desc: null
  value: 4
Dropout Rate:
  desc: null
  value: 0.5
Dataset:
  desc: null
  value: mhessel/newyorker_caption_contest
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713068699.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
