TRAIN:
  ENABLE: True
  BATCH_SIZE: 4
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  EPOCHS: 3
TEST:
  BATCH_SIZE: 4
  NUM_ITER: 10
MODEL:
  ARCH: opt_2_7
  DROPOUT_RATE: 0.5
  OUTPUT_DIR: ""
DATA:
  DATASET: mhessel/newyorker_caption_contest
  ANNOTATION: explanation
  FEATURE: image_description